version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis  # 显式指定 Redis 主机为 service 名称
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    ports:
      - "4777:4777"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --requirepass 123456  # 设置 Redis 密码
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: