version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4777:4777"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --requirepass 123456  # 设置 Redis 密码
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: